version: "2"

services:
  rabbitmq:
    image: "bitnami/rabbitmq:3.8"
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/bitnami"
      
  apache:
    image: 'bitnami/apache:latest'
    user: root
    ports:
      - '5000:5000'
    environment:
      - APACHE_HTTP_PORT_NUMBER=5000
    volumes:
      - ./frontend:/app

  mysql:
    image: mysql
    #image: "bitnami/mysql:8.0"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3300:3306"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=sam@sam
      - MYSQL_DATABASE=buytradedb
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
      - MYSQL_USER=sam
      - MYSQL_PASSWORD=sam@sam
  python:
    build:
      context: .
      dockerfile: ./dockerfile

    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - rabbitmq
      - mysql
    links:
      - mysql:mysql
    volumes:
      - ./backend:/usr/src/app
volumes:
  rabbitmq_data:
    driver: local
