version: '3'
services:
    messaging:
        image: 'rabbitmq:3-management'
    mysql:
        image: 'mysql'
        environment:
            MYSQL_USER: bhanav
            MYSQL_ROOT_PASSWORD: bhanav
    front_end:
        build: ./front_end
        ports:
            - 5000:5000
          
