version: "3"

services:
  rabbitmq:
    image: "bitnami/rabbitmq:3.8"
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/bitnami"

  rabbitmq1:
    image: "bitnami/rabbitmq:3.8"
    links:
        - rabbitmq
    restart: unless-stopped        
    ports:
      - "4368:4369"
      - "5671:5672"
      - "25671:25672"
      - "15671:15672"
    volumes:
      - "rabbitmq_data:/bitnami"

  rabbitmq2:
    image: "bitnami/rabbitmq:3.8"
    links:
        - rabbitmq
        - rabbitmq1
    restart: unless-stopped
    ports:
      - "4367:4369"
      - "5670:5672"
      - "25670:25672"
      - "15670:15672"
    volumes:
      - "rabbitmq_data:/bitnami"

  apache:
    image: 'bitnami/apache:latest'
    user: root
    ports:
      - '5000:5000'
    environment:
      - APACHE_HTTP_PORT_NUMBER=5000
    volumes:
      - ./frontend:/app


  mysql:
    image: mysql
    #image: "bitnami/mysql:8.0"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3300:3306"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=sam@sam
      - MYSQL_DATABASE=buytradedb
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
      - MYSQL_USER=sam
      - MYSQL_PASSWORD=sam@sam
      
      
  mysql1:
    image: mysql
    #image: "bitnami/mysql:8.0"
    command: --default-authentication-plugin=mysql_native_password
    links:
        - mysql
    ports:
      - "3301:3306"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=sam@sam
      - MYSQL_DATABASE=buytradedb
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
      - MYSQL_USER=sam
      - MYSQL_PASSWORD=sam@sam
      
      
  mysql2:
    image: mysql
    #image: "bitnami/mysql:8.0"
    command: --default-authentication-plugin=mysql_native_password
    links:
        - mysql
        - mysql1
    ports:
      - "3302:3306"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=sam@sam
      - MYSQL_DATABASE=buytradedb
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
      - MYSQL_USER=sam
      - MYSQL_PASSWORD=sam@sam
  python:
    build:
      context: .
      dockerfile: ./dockerfile

    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - rabbitmq
      - rabbitmq1
      - rabbitmq2
      - mysql
      - mysql1
      - mysql2
    links:
      - mysql:mysql
      - mysql1:mysql1
      - mysql2:mysql2
    volumes:
      - ./backend:/usr/src/app
volumes:
  rabbitmq_data:
    driver: local
