---
apiVersion: v1
kind: Service
metadata:
  name: back-end
  labels:
    app: back-end
spec:
  type: LoadBalancer
  selector:
    app: back-end
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 32001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
  labels:
    app: back-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back-end
  template:
    metadata:
      labels:
        app: back-end
    spec:
      containers:
        - name: back-end
          image: back-end:v1
          ports:
           - name: http
             containerPort: 5001