#tag::pv-claims[]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-primary-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512M

#end::pv-claims[]

#tag::services[]
---
apiVersion: v1
kind: Service
metadata:
  name: db-rw
  labels:
    app: db-rw
spec:
  selector:
    app: db-rw
  ports:
    - protocol: TCP
      port: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: db-r
  labels:
    app: db-r
spec:
  selector:
    app: db-r
  ports:
    - protocol: TCP
      port: 3306
#end::services[]

#tag::db-rw-deployment[]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-rw
  labels:
    app: db-rw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-rw
  template:
    metadata:
      labels:
        app: db-rw
    spec:
      #securityContext:
      #  runAsUser: 999
      #  fsGroup: 999
      containers:
        - name: db-rw
          image: mysql
          env: 
            - name: MYSQL_ROOT_USER
              value: "root"
            - name: MYSQL_ROOT_PASSWORD
              value: "sam@sam"
            - name: MYSQL_ROOT_USER
              value: "root"
            - name: MYSQL_ROOT_PASSWORD
              value: sam@sam
            - name: MYSQL_DATABASE
              value: buytradedb
            - name: MYSQL_AUTHENTICATION_PLUGIN
              value: mysql_native_password
            - name: MYSQL_USER
              value: sam
            - name: MYSQL_PASSWORD
              value: sam@sam
          args: ["--default-authentication-plugin=mysql_native_password"]
          #command:
          #  - bash
          #  - "-c"
          #  - |
          #    set -ex
          #     mysqld &
          #     sleep 30
          #     mysql -u root -p sam@sam -e "CREATE TABLE IF NOT EXISTS `user` ( `ID` INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, `UserName` VARCHAR(30) NOT NULL , `Email` VARCHAR(50) NOT NULL , `Password` VARCHAR(10) NOT NULL , `Address` VARCHAR(500) NULL , `ContactNo` BIGINT(15) NULL , `CreatedDate` DATETIME NOT NULL ) ENGINE = InnoDB; CREATE TABLE IF NOT EXISTS `tokens` (`id` INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, `user_id` INT(6) , `token` VARCHAR(50)  );"
#          ports:
#            - "3300:3306"
          volumeMounts:
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: initdb
          configMap:
            name: initdb-config

#end::db-rw-deployment[]

#tag::db-r-deployment[]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-r
  labels:
    app: db-r
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db-r
  template:
    metadata:
      labels:
        app: db-r
    spec:
      containers:
        - name: db-r
          image: mysql
          env: 
            - name: MYSQL_ROOT_USER
              value: "root"
            - name: MYSQL_ROOT_PASSWORD
              value: "sam@sam"
            - name: MYSQL_ROOT_USER
              value: "root"
            - name: MYSQL_ROOT_PASSWORD
              value: sam@sam
            - name: MYSQL_DATABASE
              value: buytradedb
            - name: MYSQL_AUTHENTICATION_PLUGIN
              value: mysql_native_password
            - name: MYSQL_USER
              value: sam
            - name: MYSQL_PASSWORD
              value: sam@sam
          args: ["--default-authentication-plugin=mysql_native_password"]
          volumeMounts:
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
            - name: db-primary-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: initdb
          configMap:
            name: initdb-config
        - name: db-primary-storage
          persistentVolumeClaim:
            claimName: db-primary-pv-claim              

#end::db-r-deployment[]     