#tag::pv-claims[]
---
apiVersion: v1
kind: Service
metadata:
  name: back-end
  labels:
    app: back-end
spec:
  type: LoadBalancer
  selector:
    app: back-end
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 32001
---
#end::pv-claims[]

#tag::services[]
---
apiVersion: v1
kind: Service
metadata:
  name: db-rw
  labels:
    app: db-rw
spec:
  selector:
    app: db-rw
  ports:
    - protocol: TCP
      port: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: db-r
  labels:
    app: db-r
spec:
  selector:
    app: db-r
  ports:
    - protocol: TCP
      port: 3306
#end::services[]
